# Generated by Django 6.0.3 on 2026-03-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('PAID', 'Paid'), ('IN_CARGO', 'In Cargo'), ('IN_UZ', 'In Uzbekistan'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Performed'), (-1, 'Cancelled'), (-2, 'Cancelled After Perform')], default=1)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('payme_created_time', models.BigIntegerField(blank=True, null=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transaction', to='shop.order')),
            ],
        ),
    ]
