# Generated by Django 6.0.3 on 2026-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_status_paymentreceipt_paymetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('RECEIPT_SUBMITTED', 'Receipt Submitted'), ('PAID', 'Paid'), ('IN_CARGO', 'In Cargo'), ('IN_UZ', 'In Uzbekistan'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='NEW', max_length=20),
        ),
    ]
